### ISSUE TITLE
密码错了

### ISSUE THREAD

**Issue by dggsec** [vncloudsco/acu807155#1]
密码错了

**Comment by vncloudsco** [comment]
try this info if you using my dockerfile
```
Email: contact@manhtuong.net

Password:  Abcd1234
```

**Comment by dggsec** [comment]
![image](https://user-images.githubusercontent.com/45778072/89967769-e42a6980-dc84-11ea-8bf3-f1bfbbc12c93.png)
感谢你的回答，不过密码还是错的

**Comment by vncloudsco** [comment]
Thank you for the report, we will check out now. Please wait for us a moment so we can investigate the cause of this issue.

**Comment by vncloudsco** [comment]
we ran the test multiple times and found no problem, you can run the docker build again to check it out!
Thank you!
